name: union
description: Union types for dart
version: 0.0.0
homepage: https://github.com/rrousselGit/union
authors:
  - Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: '>=2.6.0-dev <3.0.0'

dependencies:

dev_dependencies:
  mockito: ^4.0.0
  test:
