name: union
description: Type safe union types for dart, by using extensions from Dart 2.6
version: 0.0.0+1
homepage: https://github.com/rrousselGit/union
authors:
  - Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: '>=2.6.0-dev <3.0.0'

dev_dependencies:
  test: 1.9.3
